### ISSUE TITLE
use path property instead of name at kii_json.

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/ebisu#12]
kii_jsonのフィールドをパースする際にnameフィールドに対象の名前を入れていますが、nameフィールドはdepricatedとなっています。
pathを使うように修正してください。(pathに入るのはjsonパスなので注意)

**Comment by satoshikumano** [comment]
nameを指定してトップレベルの値を取り出すユースーケースは一般的なので、deprecatedにしたのがよくなかったかもしれません。kii_jsonのdeprecated指定をやめることを検討する。
