### ISSUE TITLE
Add update action results API 

### ISSUE THREAD

**Issue by yongpingchen** [KiiPlatform/ebisu#130]
New API

```c
tio_code_t tio_handler_udpate_action_result(
        tio_handler_t* handler,
        const char* command_id,
        const char* alias,
        const char* action_name,
        tio_bool_t succeeded,
        const char* data,
        tio_action_err_t* err);
```

**Comment by yongpingchen** [comment]
We tried to REST API to action result update. 
For example if a command with 3 actions received. 
step 1. only update action result of action 1
step 2. only update action result of action 2
Then in server, only action result of step 2 kept. 

The result is not what we want.

**Comment by naoki-akimoto** [comment]
このAPIを作成した場合、1つのアクションのレザルトだけがサーバ側に残ることが判明しました。

話し合いの結果、非同期にコマンドを処理する場合はアプリ側で tio_handler_parse_command を呼び各アクションをパースして結果を保持し、全ての結果が確定するか一定時間経過(これはアプリ側の実装次第)したら tio_handler_handle_command を呼ぶことでコマンド内の全てのアクションに対するレザルトを送信する、という結果になりました。

なのでこのAPI自体は不要となりました。
