### ISSUE TITLE
RESP HEADERが長すぎる場合の対処

### ISSUE THREAD

**Issue by satoshikumano** [KiiPlatform/ebisu#56]
#42 でRESP HEADERを読み込む際に固定長のバッファを用いるように変更した。

#55 の実装ではRESP HEADERが長すぎてバッファに入らない場合はエラーにするようにした。

レスポンスヘッダーは予告なく追加されるので、現在の方式では動いていたクライアントが突然動かなくなってしまう可能性がある。

対応案:

- RESP HEADERが長すぎてバッファに入らない場合のみDynamic allocationを要求するようにする。

- RESP HEADERが長すぎてバッファに入らない場合は次のヘッダまで読み捨てて処理を継続する
  - Status line, Content-Length, Transfer-Encoding等SDKが処理を継続するために必要とするヘッダが読み捨てられていたらエラーにして処理を停止する。

**Comment by naoki-akimoto** [comment]
追記: ステータスラインでの超過やContent-LengthまたはTransfer Encodingが読めなかった場合に対応する。

**Comment by satoshikumano** [comment]
固定長のバッファを十分なサイズ用意することは難しくなく、重要なヘッダ(Status Lin,e Content-Length/ Transfer-Encoding)それを超える場合は稀なので収まらない場合は読み飛ばす。
